<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\App.Modules.Demos.Infrastructure.Data.EF\App.Modules.Demos.Infrastructure.Persistence.EF.csproj" />
    <ProjectReference Include="..\App.Modules.Demos.Interfaces.API.REST\App.Modules.Demos.Interfaces.API.REST.csproj" />
  </ItemGroup>

</Project>
